# This is an example of the most basic config
# that will mimic what PgBouncer does in transaction mode with one server.

[general]

host = "0.0.0.0"
port = 5003
admin_username = "pgcat"
admin_password = "pgcat"

[pools.postgres]
prepared_statements_cache_size = 1000

[pools.postgres.users.0]
username = "postgres"
password = "test"
pool_size = 200
min_pool_size = 1
pool_mode = "transaction"

[pools.postgres.shards.0]
servers = [
  ["127.0.0.1", 9700, "primary"]
]
database = "postgres"

